language: php
sudo: false
before_script:
  - lib/createdb.sh -u root -c test/options.php --batch --no-password-file
  - lib/createdb.sh -u root -c test/cdb-options.php --no-dbuser --batch --no-password-file
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
script:
  - php -d error_reporting=E_ALL test/test01.php
  - php -d error_reporting=E_ALL test/test02.php
  - php -d error_reporting=E_ALL test/test03.php
  - php -d error_reporting=E_ALL test/test04.php
  - php -d error_reporting=E_ALL test/test05.php
  - php -d error_reporting=E_ALL test/test06.php
